### PR TITLE
Make `:sequential` act column-wise

### PR DESCRIPTION
**Pull request by pbrehmer**
This PR possibly improves the `:sequential` CTMRG scheme, as suggested by @Yue-Zhengyuan in #88 by updating corners and edges column-wise instead of enlarging and renormalizing all environment tensors independently in the unit cell - previously only the four spatial directions were computed sequentially, now both the spatial directions and the unit cell columns are computed sequentially. This also seems to be the convention when looking at the [literature](https://scipost.org/SciPostPhysLectNotes.25).

### CODE REVIEW

**Comment by pbrehmer** [comment]
Weirdly, I find that even for `ntasks=1` the `:sequential` mode is quite a bit slower than `:simultaneous` (for small dimensions). However, I would expect that for larger bond and environment dimensions this difference vanishes since the SVD runtime should dominate the CTMRG iterations.

**Comment by lkdvos** [comment]
Any chance you can benchmark the before and after for the sequential mode? I would love to know if we should really have both options, or can just always enforce one or the other...

**Comment by pbrehmer** [comment]
Sure I will take a look at the performance before and after making the column sequential!

What I find a bit concerning is that the tests fail for large unit cells and evaluating the energy of a random PEPS: somehow the new `:sequential` produces a slightly different result already in the 4th digit or so. On the one hand this is not surprising since the environments are really converged in a different way, but I wouldn't have expected the difference to be this big. I would assume that during optimization this effect is compensated by the optimizer somehow, so it might not be problem.

**Comment by pbrehmer** [comment]
So I played around with the old and new `:sequential` implementations and I found the new implementation to be a bit faster in the reverse pass - but keep in mind that I didn't have the time to thoroughly benchmark this.

I first ran a couple of LBFGS optimization steps with the Heisenberg Hamiltonian to "thermalize" the PEPS. Then I timed a single CTMRG iteration and the differentiation of `leading_boundary`. For $D=3$, $\chi=64$ and a 2x2 unit cell I get for the old `:sequential` implementation

Screenshot from 2024-11-06 17-12-00

The new column-wise dependent `:sequential` seems to differentiate faster and for comparison I also added the same benchmark using `:simultaneous` (which is using 4 Julia threads):

Screenshot from 2024-11-06 16-41-58

I don't really see the necessity to have both the old and new style of `:sequential` implemented and we can probably just stick with the new column-wise dependent implementation. What do you think? @lkdvos

**Comment by lkdvos** [comment]
I changed some small things to excise the "expansion" from the sequential CTMRG scheme. I'm not entirely happy with the result still, but I don't really have the time to invest here.
If the tests turn green, this is good to go for me!

Just to jot down some thoughts:

It seems like the different flavours we have currently really are wildly different, so I would even be happy to just separate them out into two files. Having the different parts of the algorithms interleaved is really more annoying than it helps to organise, I feel.

**Review by lkdvos — APPROVED** [review]

**Comment by pbrehmer** [comment]
> It seems like the different flavours we have currently really are wildly different, so I would even be happy to just separate them out into two files. Having the different parts of the algorithms interleaved is really more annoying than it helps to organise, I feel.

Yes, I definitely agree and it would probably facilitate implementing different projector algorithms anyway. I will separate the two flavors then.

**Pull request merged**
